module.exports = {
  settings: {
    bullet: '-',
    emphasis: '_',
    fences: true,
    incrementListMarker: true,
    listItemIndent: 'one',
    resourceLink: true,
    rule: '-',
    strong: '*',
  },
  plugins: [
    require('remark-preset-lint-markdown-style-guide'),
    require('remark-preset-lint-recommended'),
    [require('remark-lint-emphasis-marker'), '_'],
    [require('remark-lint-list-item-indent'), 'space'],
    [require('remark-lint-list-item-spacing'), { checkBlanks: true }],
    [require('remark-lint-ordered-list-marker-value'), 'ordered'],
    [require('remark-lint-first-heading-level'), 2],
    require('remark-lint-no-empty-url'),
    require('remark-validate-links'),
    [require('remark-lint-file-extension'), false],
    [require('remark-lint-no-file-name-articles'), false],
    [require('remark-lint-no-file-name-irregular-characters'), false],
    [require('remark-lint-blockquote-indentation'), false],
    [require('remark-lint-code-block-style'), false],
    [require('remark-lint-definition-case'), false],
    [require('remark-lint-definition-spacing'), false],
    [require('remark-lint-emphasis-marker'), false],
    [require('remark-lint-fenced-code-marker'), false],
    [require('remark-lint-final-newline'), false],
    [require('remark-lint-hard-break-spaces'), false],
    [require('remark-lint-heading-style'), false],
    [require('remark-lint-link-title-style'), false],
    [require('remark-lint-list-item-bullet-indent'), false],
    [require('remark-lint-list-item-content-indent'), false],
    [require('remark-lint-list-item-indent'), false],
    [require('remark-lint-list-item-spacing'), false],
    [require('remark-lint-maximum-line-length'), false],
    [require('remark-lint-no-blockquote-without-marker'), false],
    [require('remark-lint-no-consecutive-blank-lines'), false],
    [require('remark-lint-no-heading-content-indent'), false],
    [require('remark-lint-no-inline-padding'), false],
    [require('remark-lint-no-table-indentation'), false],
    [require('remark-lint-ordered-list-marker-style'), false],
    [require('remark-lint-ordered-list-marker-value'), false],
    [require('remark-lint-rule-style'), false],
    [require('remark-lint-strong-marker'), false],
    [require('remark-lint-table-cell-padding'), false],
    [require('remark-lint-table-pipe-alignment'), false],
    [require('remark-lint-table-pipes'), false],
    [require('remark-lint-unordered-list-marker-style'), false],
  ],
}
